name:                mini-patterns-and-deriving
version:             0.1.0.0
github:              "githubuser/mini-patterns-and-deriving"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mini-patterns-and-deriving#readme>

ghc-options:
  - -Wall

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- text
- aeson
- mtl
- hashable
library:
  source-dirs: src

executables:
  mini-patterns-and-deriving-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-patterns-and-deriving

tests:
  mini-patterns-and-deriving-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-patterns-and-deriving
